config/routes.rb
Rails.application.routes.draw do 
  resources :widgets
  resources :recipes
  get 'welcome/index'

  # resources :articles
  resources :products
  
  resources :articles do
    resources :comments
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
    has_and_belongs_to_many :courses
	validates :title, presence: true,
                    length: { minimum: 5, maximum: 100, too_long: "%{count} characters is the maximum allowed", too_short: "%{count} characters is the minimum allowed"}, uniqueness: true, format: { with: /\A[a-zA-z]+\z/, message: 'only letters are allowed' }
    validates :text, presence: true,
                    length: { minimum: 5 }
    

    
    # validates :title, 

    # validates :size, inclusion: { in: %w(small medium large),
    # message: "%{value} is not a valid size" }, allow_nil: true

    # validate :validate_age
    # before_create :greeting_message

    # def greeting_message
    #     puts "Hey! I will run before you create an object!"
    # end

    #if one line of content
    before_create do
        puts "Hey! I will run before you create an object!"
    end

    after_initialize do |article|
        puts "You have initialized an object!"
    end
     
    after_find do |article|
        puts "You have found an object!"
    end

    after_touch do |article|
        puts "You have touched an object"
    end

    #custom validation msg example
    def validate_age
        if self.date_of_birth.present?
            age = Date.today.year - self.date_of_birth
            if age < 15
                errors.add(:age, 'Please enter age grater than 15')
            end
        end
    end

    

end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
end

app/models/bicycle.rb
class Bicycle < Vehicle
end

app/models/blog1.rb
class Blog1 < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :author
end

app/models/car.rb
class Car < Vehicle
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :commenter, presence: true,
                    length: { minimum: 5 }
  validates :body, presence: true,
                    length: { minimum: 15 }
end

app/models/course.rb
class Course < ApplicationRecord
	has_and_belongs_to_many :articles
end

app/models/modelbasicpratice.rb
class Modelbasicpratice < ApplicationRecord
	# include ActiveModel::AttributeMethods
 
	# attribute_method_prefix 'reset_'
	# attribute_method_suffix '_highest?'
	# define_attribute_methods 'age'
		 
	# attr_accessor :age
		 
	# private
 #    def reset_attribute(attribute)
 #      send("#{attribute}=", 0)
 #    end
 
 #    def attribute_highest?(attribute)
 #      send(attribute) > 100
 #    end
 # include ActiveModel::Conversion
 
 #  def persisted?
 #    false
 #  end
 
 #  def id
 #    nil
 #  end
 include ActiveModel::Dirty
  define_attribute_methods :first_name, :last_name
 
  def first_name
    @first_name
  end
 
  def first_name=(value)
    first_name_will_change!
    @first_name = value
  end
 
  def last_name
    @last_name
  end
 
  def last_name=(value)
    last_name_will_change!
    @last_name = value
  end
 
  def save
    # do save work...
    changes_applied
  end
end

app/models/motorcycle.rb
class Motorcycle < Vehicle
end

app/models/person.rb
class Person < ApplicationRecord
	include ActiveModel::AttributeMethods

	include ActiveModel::SecurePassword
  	has_secure_password
  	has_secure_password :recovery_password, validations: false
 
  	attr_accessor :password_digest, :recovery_password_digest
 
	attribute_method_prefix 'reset_'
	attribute_method_suffix '_highest?'
	define_attribute_methods 'age'
	attr_accessor :age
	 
	private
    def reset_attribute(attribute)
      send("#{attribute}=", 0)
    end
 
    def attribute_highest?(attribute)
      send(attribute) > 100
    end
	
end

app/models/product.rb
class Product < ApplicationRecord
	# validates :name, presence: true,
 #                    length: { minimum: 3, maximum: 80}
 #    validates :price, presence: true,
 #                    length: { is: 5,numericality: { only_integer: true }}
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/models/widget.rb
class Widget < ApplicationRecord
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
    	@articles = Article.all
  	end
	def show
    	@article = Article.find(params[:id])
 	end
	

	
	def new
	  @article = Article.new
	end


	def edit
	  @article = Article.find(params[:id])
	end
	 
	def create
	  @article = Article.new(article_params)
	 
	  if @article.save
	    redirect_to @article
	  else
	    render 'new'
	  end
	end

	def update
	  @article = Article.find(params[:id])
	 
	  if @article.update(article_params)
	    redirect_to @article
	  else
	    render 'edit'
	   end
	end

	
	def destroy
	  @article = Article.find(params[:id])
	  @article.destroy
	 
	  redirect_to articles_path
	end

	 
	private
	  def article_params
	    params.require(:article).permit(:title, :text)
	  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<style type="text/css">
  
.field_with_errors {
  padding: 2px;
  background-color: red;
  display: table;
}
</style>
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
<!-- <p>
    <%= form.label :size %><br>
    <%= form.text_area :size %>
  </p>
 -->
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<ul>
  <li>
    <%= link_to 'Add Article', new_article_path %>
  </li>
</ul>
<h1>Articles Details</h1>
<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th>Description</th>
    <th></th>
    <th>Action</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>

      <td><%= article.title %></td>
      <td></td>
      <td><%= article.text %></td>
      <td></td>
      <td><%= link_to 'View', article_path(article) %></td>
      <td></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td></td>
      <td><%= link_to 'Delete', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<br>

<%= link_to 'Go Back', welcome_index_path %>

app/views/articles/new.html.erb
<h1>Add Article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>