config/routes.rb
Rails.application.routes.draw do 
  resources :widgets
  resources :recipes
  get 'welcome/index'

  # resources :articles
  resources :products
  
  resources :articles do
    resources :comments
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
    has_and_belongs_to_many :courses
	validates :title, presence: true,
                    length: { minimum: 5, maximum: 100, too_long: "%{count} characters is the maximum allowed", too_short: "%{count} characters is the minimum allowed"}, uniqueness: true, format: { with: /\A[a-zA-z]+\z/, message: 'only letters are allowed' }
    validates :text, presence: true,
                    length: { minimum: 5 }
    

    
    # validates :title, 

    # validates :size, inclusion: { in: %w(small medium large),
    # message: "%{value} is not a valid size" }, allow_nil: true

    # validate :validate_age
    # before_create :greeting_message

    # def greeting_message
    #     puts "Hey! I will run before you create an object!"
    # end

    #if one line of content
    before_create do
        puts "Hey! I will run before you create an object!"
    end

    after_initialize do |article|
        puts "You have initialized an object!"
    end
     
    after_find do |article|
        puts "You have found an object!"
    end

    after_touch do |article|
        puts "You have touched an object"
    end

    #custom validation msg example
    def validate_age
        if self.date_of_birth.present?
            age = Date.today.year - self.date_of_birth
            if age < 15
                errors.add(:age, 'Please enter age grater than 15')
            end
        end
    end

    

end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
end

app/models/bicycle.rb
class Bicycle < Vehicle
end

app/models/blog1.rb
class Blog1 < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :author
end

app/models/car.rb
class Car < Vehicle
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :commenter, presence: true,
                    length: { minimum: 5 }
  validates :body, presence: true,
                    length: { minimum: 15 }
end

app/models/course.rb
class Course < ApplicationRecord
	has_and_belongs_to_many :articles
end

app/models/modelbasicpratice.rb
class Modelbasicpratice < ApplicationRecord
	# include ActiveModel::AttributeMethods
 
	# attribute_method_prefix 'reset_'
	# attribute_method_suffix '_highest?'
	# define_attribute_methods 'age'
		 
	# attr_accessor :age
		 
	# private
 #    def reset_attribute(attribute)
 #      send("#{attribute}=", 0)
 #    end
 
 #    def attribute_highest?(attribute)
 #      send(attribute) > 100
 #    end
 # include ActiveModel::Conversion
 
 #  def persisted?
 #    false
 #  end
 
 #  def id
 #    nil
 #  end
 include ActiveModel::Dirty
  define_attribute_methods :first_name, :last_name
 
  def first_name
    @first_name
  end
 
  def first_name=(value)
    first_name_will_change!
    @first_name = value
  end
 
  def last_name
    @last_name
  end
 
  def last_name=(value)
    last_name_will_change!
    @last_name = value
  end
 
  def save
    # do save work...
    changes_applied
  end
end

app/models/motorcycle.rb
class Motorcycle < Vehicle
end

app/models/person.rb
class Person < ApplicationRecord
	include ActiveModel::AttributeMethods

	include ActiveModel::SecurePassword
  	has_secure_password
  	has_secure_password :recovery_password, validations: false
 
  	attr_accessor :password_digest, :recovery_password_digest
 
	attribute_method_prefix 'reset_'
	attribute_method_suffix '_highest?'
	define_attribute_methods 'age'
	attr_accessor :age
	 
	private
    def reset_attribute(attribute)
      send("#{attribute}=", 0)
    end
 
    def attribute_highest?(attribute)
      send(attribute) > 100
    end
	
end

app/models/product.rb
class Product < ApplicationRecord
	# validates :name, presence: true,
 #                    length: { minimum: 3, maximum: 80}
 #    validates :price, presence: true,
 #                    length: { is: 5,numericality: { only_integer: true }}
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/models/widget.rb
class Widget < ApplicationRecord
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
      @product = Product.all
    end
  def show
      @product = Product.find(params[:id])
  end
  
  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end


  def create
    @product = Product.new(product_params)
     respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }

      else
        render 'new', layout: false
      end
    end
  end

  def update
    @product = Product.find(params[:id])
   
    if @product.update(product_params)
      redirect_to @product
      # render action: "index"

      # redirect_to @product,status: 500
      # redirect_back(fallback_location: @product_path)
      # render json: @product
      # render js: "alert('Hello Rails');"
      # render file: "#{Rails.root}/public/404.html", layout: false
    else
      render 'edit'
     end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
   
    redirect_to products_path
  end



  private
    def product_params
      params.require(:product).permit(:name, :price, :description, :expiry_date,)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/products/_box.html.erb
<div class='box'>
  <%= yield %>
</div>

app/views/products/_form.html.erb
<%= form_with model: @product, local: true do |form| %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
 
	<p>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </p>
  <p>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.label :expiry_date %>
    <%= form.date_field :expiry_date %>
  </p>

  


  
  <p>
    <%= form.submit %>
  </p>
  <p>
    <%= link_to 'Go Back', products_path %>

  </p>
 
<% end %>

app/views/products/edit.html.erb
<h1>Update Product</h1>
 
<%= render 'form' %>

app/views/products/index.html.erb
<style type="text/css">
  table,th,td {
    border:1px solid black;
    border-collapse: collapse;
  }
</style>
<button><%= link_to 'Add Product', new_product_path %></button>
<h1>Cosmetic Product Details</h1>
<table>
    <thead>
        <tr>
          <th>Sr.no.</th>
          <th>Name</th>
          <th>Price <small>(In $)</small></th>
          <th>Description</th>
          <th>Expiry Date</th>
          <th colspan="3">Action</th>
        </tr>
      
    </thead>
 <%= 
    # number_to_currency(1234567890) 
    # number_to_human_size(1234)
    # number_to_human_size(1234567)
    # number_to_percentage(100, precision: 0)
    # number_to_phone(9876543210)
    # number_with_delimiter(9876543210)
  %>
  <%
  @srno = 0
  @product.each do |product| 
    @srno = @srno + 1
  %>
    <tr>
      <td><%= @srno %></td>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= product.description %></td>
      <td><%= product.expiry_date %></td>
      <td><button><%= link_to 'View', product %></button></td>
      <td><button><%= link_to 'Edit', edit_product_path(product) %></button></td>
      <td><button><%= link_to 'Delete', product_path(product),
              method: :delete,
              data: { confirm: 'Are you sure,you want to delete?' } %></button></td>
    </tr>
  <% end %>
</table>
<br>
<button><%= link_to 'Go Back', welcome_index_path %></button>

app/views/products/new.html.erb
<h3>Add Product</h3>

<%= render partial: "form" %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<h3>View Product Details</h3>
<%= render partial: 'layoutbox', layout: 'box', locals: { product: @product } %>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<p>
  <strong>Expiry Date:</strong>
  <%= @product.expiry_date %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
 

 
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/view_product.html.erb
<h1>Products#view_product</h1>
<p>Find me in app/views/products/view_product.html.erb</p>